import React, {useMemo, useState} from "react";
import { createRoot } from "react-dom/client";
import { Home, Utensils, Dumbbell, TrendingUp, Settings, Plus, ChevronRight, Flame, Droplets, Trophy, Trash2, X, Pencil, Check, Image as ImageIcon } from "lucide-react";
import "./styles.css";

const todayKey=()=>new Date().toISOString().slice(0,10);
const STORAGE="nfit-v3", OLD_STORAGE="nfit-v2";
const defaultExercises={
 Chest:["Bench Press","Incline Dumbbell Press","Cable Fly","Pec Deck","Chest Press Machine","Dumbbell Fly"],
 Back:["Lat Pulldown","Seated Cable Row","One-Arm Dumbbell Row","Barbell Row","Straight-Arm Pulldown","Back Extension"],
 Shoulders:["Overhead Press","Dumbbell Shoulder Press","Lateral Raise","Rear Delt Fly","Face Pull","Front Raise"],
 Biceps:["Barbell Curl","Dumbbell Curl","Hammer Curl","Incline Dumbbell Curl","Cable Curl","Preacher Curl"],
 Triceps:["Cable Pushdown","Overhead Triceps Extension","Skull Crusher","Rope Pushdown","Dips","Close-Grip Bench Press"],
 Legs:["Barbell Squat","Leg Press","Romanian Deadlift","Leg Extension","Leg Curl","Walking Lunges","Calf Raise"]
};
const weightOptions=Array.from({length:81},(_,i)=>(i+1)*2.5), repOptions=Array.from({length:40},(_,i)=>i+1);
const ingredientDatabase=[
 {id:"egg",name:"Egg",unit:"piece",cal:72,protein:6.3,fat:4.8,carbs:.4},
 {id:"ghee",name:"Ghee",unit:"tbsp",cal:126,protein:0,fat:14,carbs:0},
 {id:"oil",name:"Cooking oil",unit:"tbsp",cal:119,protein:0,fat:13.5,carbs:0},
 {id:"tomato",name:"Tomato",unit:"g",base:100,cal:18,protein:.9,fat:.2,carbs:3.9},
 {id:"onion",name:"Onion",unit:"g",base:100,cal:40,protein:1.1,fat:.1,carbs:9.3},
 {id:"chilli",name:"Green chilli",unit:"g",base:100,cal:40,protein:1.9,fat:.4,carbs:8.8},
 {id:"besan",name:"Besan",unit:"g",base:100,cal:387,protein:22,fat:6.7,carbs:58},
 {id:"chicken",name:"Chicken breast (cooked)",unit:"g",base:100,cal:165,protein:31,fat:3.6,carbs:0},
 {id:"rice",name:"Cooked rice",unit:"g",base:100,cal:130,protein:2.7,fat:.3,carbs:28},
 {id:"roti",name:"Roti",unit:"piece",cal:120,protein:3.5,fat:3,carbs:18},
 {id:"milk",name:"Milk",unit:"ml",base:100,cal:61,protein:3.2,fat:3.3,carbs:4.8},
 {id:"banana",name:"Banana",unit:"piece",cal:105,protein:1.3,fat:.4,carbs:27},
 {id:"peanut",name:"Peanuts",unit:"g",base:100,cal:567,protein:25.8,fat:49.2,carbs:16.1},
 {id:"curd",name:"Curd",unit:"g",base:100,cal:61,protein:3.5,fat:3.3,carbs:4.7},
 {id:"paneer",name:"Paneer",unit:"g",base:100,cal:265,protein:18.3,fat:20.8,carbs:1.2},
 {id:"potato",name:"Potato",unit:"g",base:100,cal:77,protein:2,fat:.1,carbs:17.5},
 {id:"oats",name:"Oats",unit:"g",base:100,cal:389,protein:16.9,fat:6.9,carbs:66.3},
 {id:"dal",name:"Cooked dal",unit:"g",base:100,cal:116,protein:9,fat:.4,carbs:20},
 {id:"bread",name:"Bread",unit:"piece",cal:75,protein:2.7,fat:1,carbs:14},
 {id:"apple",name:"Apple",unit:"piece",cal:95,protein:.5,fat:.3,carbs:25},
 {id:"peanutbutter",name:"Peanut butter",unit:"tbsp",cal:94,protein:4,fat:8,carbs:3.2},
 {id:"sugar",name:"Sugar",unit:"g",base:100,cal:387,protein:0,fat:0,carbs:100}
];
const defaultRecipes=[{id:"egg-bhurji",name:"Egg Bhurji",ingredients:[{id:"egg",amount:2},{id:"ghee",amount:2},{id:"tomato",amount:50},{id:"onion",amount:30},{id:"chilli",amount:5}]}];
const defaultData={weight:49,goalWeight:60,calGoal:2700,proteinGoal:130,waterGoal:2.5,foodByDay:{},workoutsByDay:{},weightHistory:[{date:todayKey(),weight:49}],waterByDay:{},exerciseLibrary:defaultExercises,recipes:defaultRecipes,finishedWorkouts:{}};
function mergeData(raw){const d={...defaultData,...(raw||{})};d.exerciseLibrary=raw?.exerciseLibrary||defaultExercises;d.recipes=raw?.recipes||defaultRecipes;d.finishedWorkouts=raw?.finishedWorkouts||{};return d}
function load(){try{const c=localStorage.getItem(STORAGE);if(c)return mergeData(JSON.parse(c));const o=localStorage.getItem(OLD_STORAGE);if(o)return mergeData(JSON.parse(o))}catch{}return defaultData}
function save(d){localStorage.setItem(STORAGE,JSON.stringify(d))}
function uid(){return crypto.randomUUID?.()||String(Date.now()+Math.random())}
function nutritionForIngredient(item,amount){const factor=item.unit==="piece"||item.unit==="tbsp"?Number(amount):Number(amount)/(item.base||100);return{cal:item.cal*factor,protein:item.protein*factor,fat:item.fat*factor,carbs:item.carbs*factor}}
function calcIngredients(items){return items.reduce((a,x)=>{const d=ingredientDatabase.find(i=>i.id===x.id);if(!d)return a;const n=nutritionForIngredient(d,x.amount);return{cal:a.cal+n.cal,protein:a.protein+n.protein,fat:a.fat+n.fat,carbs:a.carbs+n.carbs}},{cal:0,protein:0,fat:0,carbs:0})}
function foodItem(name,qty,n,recipe=false,ingredients=[]){return{id:uid(),name,qty,cal:n.cal,protein:n.protein,fat:n.fat,carbs:n.carbs,recipe,ingredients}}

function App(){
 const[tab,setTab]=useState("home"),[data,setData]=useState(load),day=todayKey();
 const update=patch=>setData(prev=>{const next={...prev,...patch};save(next);return next});
 const food=data.foodByDay[day]||[], workout=data.workoutsByDay[day]||{};
 const totals=useMemo(()=>food.reduce((a,f)=>({cal:a.cal+f.cal,protein:a.protein+f.protein,fat:a.fat+f.fat,carbs:a.carbs+f.carbs}),{cal:0,protein:0,fat:0,carbs:0}),[food]);
 const addFood=item=>update({foodByDay:{...data.foodByDay,[day]:[...food,item]}}), removeFood=id=>update({foodByDay:{...data.foodByDay,[day]:food.filter(f=>f.id!==id)}});
 const addWeight=w=>update({weight:w,weightHistory:[...(data.weightHistory||[]),{date:day,weight:w}]});
 const water=data.waterByDay[day]||0, addWater=()=>update({waterByDay:{...data.waterByDay,[day]:Math.min(data.waterGoal,water+.25)}});
 return <div className="app"><header className="topbar"><div><div className="eyebrow">PERSONAL FITNESS</div><h1>N-FIT</h1></div><div className="avatar">N</div></header><main>
  {tab==="home"&&<HomePage data={data} totals={totals} water={water} setTab={setTab} addWater={addWater}/>} {tab==="food"&&<FoodPage food={food} totals={totals} addFood={addFood} removeFood={removeFood}/>} {tab==="workout"&&<WorkoutPage data={data} workout={workout} updateData={update}/>} {tab==="progress"&&<ProgressPage data={data} addWeight={addWeight}/>} {tab==="settings"&&<SettingsPage data={data} update={update}/>}</main>
  <nav className="nav">{[["home",Home,"Home"],["food",Utensils,"Food"],["workout",Dumbbell,"Train"],["progress",TrendingUp,"Progress"],["settings",Settings,"Settings"]].map(([id,I,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><I size={20}/><span>{label}</span></button>)}</nav></div>
}
function HomePage({data,totals,water,setTab,addWater}){const pct=Math.min(100,Math.round(totals.cal/data.calGoal*100)),finished=data.finishedWorkouts?.[todayKey()];return <section className="page"><div className="welcome"><span>{new Date().toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long"})}</span><strong>Keep showing up.</strong></div><div className="heroCard"><div><span className="label">CURRENT WEIGHT</span><div className="big">{Number(data.weight).toFixed(1)} <small>kg</small></div></div><div className="goal">GOAL <b>{data.goalWeight} kg</b></div></div><div className="sectionTitle"><h2>Today</h2><span>{pct}% calories</span></div><div className="macroGrid"><Macro icon={<Flame size={18}/>} value={Math.round(totals.cal)} suffix={`/ ${data.calGoal} kcal`} label="Calories" pct={pct}/><Macro icon={<Trophy size={18}/>} value={`${totals.protein.toFixed(1)}g`} suffix={`/ ${data.proteinGoal}g`} label="Protein" pct={Math.min(100,totals.protein/data.proteinGoal*100)}/></div><div className="card workoutCard"><div className="cardHead"><div><span className="label">TODAY'S TRAINING</span><h2>{finished?"Workout completed ✓":"Build your session"}</h2></div><Dumbbell size={24}/></div><p>{finished?`Finished at ${finished.time}. Your workout is saved.`:"Choose from your saved exercise library and log each set."}</p><button className="primary" onClick={()=>setTab("workout")}>{finished?"VIEW WORKOUT":"START WORKOUT"}<ChevronRight size={18}/></button></div><div className="quickGrid"><button onClick={()=>setTab("food")}><Utensils/><b>Add food</b><span>Recipes + foods</span></button><button onClick={()=>setTab("progress")}><TrendingUp/><b>Log weight</b><span>Track progress</span></button></div><div className="card hydration"><Droplets/><div><b>Water</b><span>{water.toFixed(2)} / {data.waterGoal} L</span></div><button onClick={addWater}>+ 250 ml</button></div></section>}
function Macro({icon,value,suffix,label,pct}){return <div className="macro">{icon}<b>{value}</b><span>{suffix}</span><div className="bar"><i style={{width:pct+"%"}}/></div><small>{label}</small></div>}

function IngredientEditor({items,setItems}){const add=()=>setItems([...items,{id:"tomato",amount:50}]);const upd=(i,p)=>setItems(items.map((x,j)=>j===i?{...x,...p}:x));return <><div className="builderHead"><b>Ingredients</b><span>No calories/protein to enter</span></div>{items.map((x,i)=>{const d=ingredientDatabase.find(a=>a.id===x.id)||ingredientDatabase[0];return <div className="ingredientRow" key={i}><select value={x.id} onChange={e=>upd(i,{id:e.target.value})}>{ingredientDatabase.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input inputMode="decimal" value={x.amount} onChange={e=>upd(i,{amount:e.target.value})}/><span>{d.unit}</span><button className="iconBtn" onClick={()=>setItems(items.filter((_,j)=>j!==i))}><X size={16}/></button></div>})}<button className="addIngredient" onClick={add}>+ ADD INGREDIENT</button></>}
function FoodPage({food,totals,addFood,removeFood}){const[show,setShow]=useState(false),[mode,setMode]=useState("recipe"),[name,setName]=useState(""),[ingredients,setIngredients]=useState(defaultRecipes[0].ingredients.map(x=>({...x})));const n=calcIngredients(ingredients);const addRecipe=()=>{const clean=ingredients.filter(x=>Number(x.amount)>0);if(!name.trim()||!clean.length)return;addFood(foodItem(name.trim(),"1 serving",n,true,clean.map(x=>{const d=ingredientDatabase.find(i=>i.id===x.id);return `${x.amount} ${d.unit} ${d.name}`})));setShow(false);setName("")};return <section className="page"><div className="pageTitle"><div><span className="label">NUTRITION</span><h2>Food log</h2></div><button className="round" onClick={()=>setShow(!show)}><Plus/></button></div><div className="nutritionHero"><div><span>CALORIES</span><strong>{Math.round(totals.cal)}</strong><small>kcal today</small></div><div><span>PROTEIN</span><strong>{totals.protein.toFixed(1)}g</strong><small>logged today</small></div></div>{show&&<div className="addPanel card"><div className="modeTabs"><button className={mode==="recipe"?"sel":""} onClick={()=>setMode("recipe")}>Build a recipe</button><button className={mode==="manual"?"sel":""} onClick={()=>setMode("manual")}>Quick food</button></div>{mode==="recipe"?<div className="recipeBuilder"><label>RECIPE NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Egg Bhurji"/></label><IngredientEditor items={ingredients} setItems={setIngredients}/><div className="autoNutrition"><div><span>CALORIES</span><b>{Math.round(n.cal)} kcal</b></div><div><span>PROTEIN</span><b>{n.protein.toFixed(1)} g</b></div><div><span>FAT</span><b>{n.fat.toFixed(1)} g</b></div><div><span>CARBS</span><b>{n.carbs.toFixed(1)} g</b></div></div><button className="primary" onClick={addRecipe}>ADD TO TODAY</button><p className="helper">Example: Egg Bhurji → 2 eggs + 2 tbsp ghee + 50 g tomato + 30 g onion + 5 g chilli. N-FIT calculates everything automatically.</p></div>:<QuickFood addFood={addFood}/>}</div>}<div className="sectionTitle"><h2>Today's food</h2><span>{food.length} items</span></div><div className="list">{food.length===0?<div className="empty">No food logged yet. Tap + to build a recipe.</div>:food.map(f=><div className="foodRow" key={f.id}><div className="foodIcon">{f.recipe?"🍳":"🍽️"}</div><div className="grow"><b>{f.name}</b><span>{f.qty}</span>{f.recipe&&<small className="ingredients">{f.ingredients.join(" · ")}</small>}</div><div className="foodMacros"><b>{Math.round(f.cal)}</b><span>{f.protein.toFixed(1)}g P</span></div><button className="iconBtn" onClick={()=>removeFood(f.id)}><Trash2 size={16}/></button></div>)}</div></section>}
function QuickFood({addFood}){const[name,setName]=useState(""),[items,setItems]=useState([{id:"banana",amount:1}]),n=calcIngredients(items);const add=()=>{if(!name.trim())return;addFood(foodItem(name,"1 serving",n,false,items.map(x=>{const d=ingredientDatabase.find(i=>i.id===x.id);return `${x.amount} ${d.unit} ${d.name}`})));setName("")};return <div className="recipeBuilder"><label>FOOD NAME<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Banana shake"/></label><IngredientEditor items={items} setItems={setItems}/><div className="autoNutrition"><div><span>CALORIES</span><b>{Math.round(n.cal)} kcal</b></div><div><span>PROTEIN</span><b>{n.protein.toFixed(1)} g</b></div></div><button className="primary" onClick={add}>ADD TO TODAY</button></div>}

function ExerciseIllustration({name}){
 const n=name.toLowerCase();
 let type="press";
 if(n.includes("squat")||n.includes("leg press")||n.includes("lunge")||n.includes("leg extension")||n.includes("leg curl")||n.includes("calf")) type="legs";
 else if(n.includes("pulldown")||n.includes("row")||n.includes("back extension")) type="pull";
 else if(n.includes("curl")||n.includes("hammer")) type="curl";
 else if(n.includes("lateral")||n.includes("rear delt")||n.includes("face pull")||n.includes("shoulder")||n.includes("overhead")) type="shoulder";
 else if(n.includes("fly")||n.includes("pec deck")) type="fly";

 const Frame=({x,children})=><g transform={`translate(${x} 0)`}>{children}</g>;
 const person=(cx=35,cy=43)=> <circle cx={cx} cy={cy} r="6" className="ill-head"/>;
 return <div className="exerciseMini">
   <div className="miniLabel">HOW TO <span>• {name}</span></div>
   <svg viewBox="0 0 270 82" role="img" aria-label={`${name} form illustration`}>
    <line x1="8" y1="70" x2="262" y2="70" className="ill-floor"/>
    {type==="press" && <>
      <Frame x={0}>{person(32,38)}<line x1="37" y1="43" x2="55" y2="57" className="ill-body"/><line x1="52" y1="57" x2="43" y2="68" className="ill-body"/><line x1="52" y1="57" x2="64" y2="68" className="ill-body"/><line x1="48" y1="52" x2="72" y2="40" className="ill-body"/><line x1="69" y1="40" x2="69" y2="30" className="ill-bar"/><line x1="60" y1="30" x2="78" y2="30" className="ill-bar"/><line x1="18" y1="61" x2="78" y2="61" className="ill-bench"/></Frame>
      <Frame x={90}>{person(32,38)}<line x1="37" y1="43" x2="55" y2="57" className="ill-body"/><line x1="52" y1="57" x2="43" y2="68" className="ill-body"/><line x1="52" y1="57" x2="64" y2="68" className="ill-body"/><line x1="48" y1="52" x2="72" y2="52" className="ill-body"/><line x1="69" y1="52" x2="69" y2="27" className="ill-bar"/><line x1="60" y1="27" x2="78" y2="27" className="ill-bar"/><line x1="18" y1="61" x2="78" y2="61" className="ill-bench"/></Frame>
      <Frame x={180}>{person(32,38)}<line x1="37" y1="43" x2="55" y2="57" className="ill-body"/><line x1="52" y1="57" x2="43" y2="68" className="ill-body"/><line x1="52" y1="57" x2="64" y2="68" className="ill-body"/><line x1="48" y1="52" x2="72" y2="40" className="ill-body"/><line x1="69" y1="40" x2="69" y2="30" className="ill-bar"/><line x1="60" y1="30" x2="78" y2="30" className="ill-bar"/><line x1="18" y1="61" x2="78" y2="61" className="ill-bench"/></Frame>
    </>}
    {type==="pull" && <>
      <Frame x={0}>{person(36,43)}<line x1="36" y1="49" x2="36" y2="62" className="ill-body"/><line x1="36" y1="52" x2="23" y2="43" className="ill-body"/><line x1="23" y1="43" x2="23" y2="29" className="ill-body"/><line x1="36" y1="52" x2="49" y2="43" className="ill-body"/><line x1="49" y1="43" x2="49" y2="29" className="ill-body"/><line x1="15" y1="26" x2="57" y2="26" className="ill-bar"/></Frame>
      <Frame x={90}>{person(36,43)}<line x1="36" y1="49" x2="36" y2="62" className="ill-body"/><line x1="36" y1="52" x2="29" y2="45" className="ill-body"/><line x1="29" y1="45" x2="29" y2="33" className="ill-body"/><line x1="36" y1="52" x2="43" y2="45" className="ill-body"/><line x1="43" y1="45" x2="43" y2="33" className="ill-body"/><line x1="15" y1="26" x2="57" y2="26" className="ill-bar"/></Frame>
      <Frame x={180}>{person(36,43)}<line x1="36" y1="49" x2="36" y2="62" className="ill-body"/><line x1="36" y1="52" x2="23" y2="43" className="ill-body"/><line x1="23" y1="43" x2="23" y2="29" className="ill-body"/><line x1="36" y1="52" x2="49" y2="43" className="ill-body"/><line x1="49" y1="43" x2="49" y2="29" className="ill-body"/><line x1="15" y1="26" x2="57" y2="26" className="ill-bar"/></Frame>
    </>}
    {type==="legs" && <>
      <Frame x={0}>{person(36,37)}<line x1="36" y1="43" x2="36" y2="54" className="ill-body"/><line x1="36" y1="46" x2="22" y2="50" className="ill-body"/><line x1="36" y1="46" x2="50" y2="50" className="ill-body"/><line x1="36" y1="54" x2="26" y2="68" className="ill-body"/><line x1="36" y1="54" x2="46" y2="68" className="ill-body"/><line x1="15" y1="42" x2="57" y2="42" className="ill-bar"/></Frame>
      <Frame x={90}>{person(36,42)}<line x1="36" y1="48" x2="36" y2="57" className="ill-body"/><line x1="36" y1="50" x2="22" y2="54" className="ill-body"/><line x1="36" y1="50" x2="50" y2="54" className="ill-body"/><line x1="36" y1="57" x2="25" y2="64" className="ill-body"/><line x1="36" y1="57" x2="47" y2="64" className="ill-body"/><line x1="15" y1="47" x2="57" y2="47" className="ill-bar"/></Frame>
      <Frame x={180}>{person(36,37)}<line x1="36" y1="43" x2="36" y2="54" className="ill-body"/><line x1="36" y1="46" x2="22" y2="50" className="ill-body"/><line x1="36" y1="46" x2="50" y2="50" className="ill-body"/><line x1="36" y1="54" x2="26" y2="68" className="ill-body"/><line x1="36" y1="54" x2="46" y2="68" className="ill-body"/><line x1="15" y1="42" x2="57" y2="42" className="ill-bar"/></Frame>
    </>}
    {type==="curl" && <>
      <Frame x={0}>{person(36,36)}<line x1="36" y1="42" x2="36" y2="58" className="ill-body"/><line x1="36" y1="47" x2="22" y2="56" className="ill-body"/><line x1="36" y1="47" x2="50" y2="56" className="ill-body"/><line x1="36" y1="58" x2="28" y2="68" className="ill-body"/><line x1="36" y1="58" x2="44" y2="68" className="ill-body"/><line x1="19" y1="59" x2="27" y2="54" className="ill-bar"/><line x1="45" y1="54" x2="53" y2="59" className="ill-bar"/></Frame>
      <Frame x={90}>{person(36,36)}<line x1="36" y1="42" x2="36" y2="58" className="ill-body"/><line x1="36" y1="47" x2="30" y2="57" className="ill-body"/><line x1="36" y1="47" x2="42" y2="57" className="ill-body"/><line x1="36" y1="58" x2="28" y2="68" className="ill-body"/><line x1="36" y1="58" x2="44" y2="68" className="ill-body"/><line x1="27" y1="57" x2="20" y2="52" className="ill-bar"/><line x1="45" y1="57" x2="52" y2="52" className="ill-bar"/></Frame>
      <Frame x={180}>{person(36,36)}<line x1="36" y1="42" x2="36" y2="58" className="ill-body"/><line x1="36" y1="47" x2="22" y2="56" className="ill-body"/><line x1="36" y1="47" x2="50" y2="56" className="ill-body"/><line x1="36" y1="58" x2="28" y2="68" className="ill-body"/><line x1="36" y1="58" x2="44" y2="68" className="ill-body"/><line x1="19" y1="59" x2="27" y2="54" className="ill-bar"/><line x1="45" y1="54" x2="53" y2="59" className="ill-bar"/></Frame>
    </>}
    {type==="shoulder" && <>
      <Frame x={0}>{person(36,36)}<line x1="36" y1="42" x2="36" y2="58" className="ill-body"/><line x1="36" y1="48" x2="20" y2="37" className="ill-body"/><line x1="36" y1="48" x2="52" y2="37" className="ill-body"/><line x1="36" y1="58" x2="28" y2="68" className="ill-body"/><line x1="36" y1="58" x2="44" y2="68" className="ill-body"/><line x1="17" y1="35" x2="24" y2="39" className="ill-bar"/><line x1="48" y1="39" x2="55" y2="35" className="ill-bar"/></Frame>
      <Frame x={90}>{person(36,36)}<line x1="36" y1="42" x2="36" y2="58" className="ill-body"/><line x1="36" y1="48" x2="18" y2="48" className="ill-body"/><line x1="36" y1="48" x2="54" y2="48" className="ill-body"/><line x1="36" y1="58" x2="28" y2="68" className="ill-body"/><line x1="36" y1="58" x2="44" y2="68" className="ill-body"/><line x1="15" y1="48" x2="25" y2="48" className="ill-bar"/><line x1="47" y1="48" x2="57" y2="48" className="ill-bar"/></Frame>
      <Frame x={180}>{person(36,36)}<line x1="36" y1="42" x2="36" y2="58" className="ill-body"/><line x1="36" y1="48" x2="20" y2="37" className="ill-body"/><line x1="36" y1="48" x2="52" y2="37" className="ill-body"/><line x1="36" y1="58" x2="28" y2="68" className="ill-body"/><line x1="36" y1="58" x2="44" y2="68" className="ill-body"/><line x1="17" y1="35" x2="24" y2="39" className="ill-bar"/><line x1="48" y1="39" x2="55" y2="35" className="ill-bar"/></Frame>
    </>}
    {type==="fly" && <>
      <Frame x={0}>{person(36,38)}<line x1="41" y1="43" x2="57" y2="57" className="ill-body"/><line x1="55" y1="57" x2="47" y2="68" className="ill-body"/><line x1="55" y1="57" x2="65" y2="68" className="ill-body"/><line x1="48" y1="50" x2="30" y2="40" className="ill-body"/><line x1="66" y1="50" x2="84" y2="40" className="ill-body"/><line x1="25" y1="38" x2="34" y2="43" className="ill-bar"/><line x1="80" y1="43" x2="89" y2="38" className="ill-bar"/><line x1="18" y1="61" x2="78" y2="61" className="ill-bench"/></Frame>
      <Frame x={90}>{person(36,38)}<line x1="41" y1="43" x2="57" y2="57" className="ill-body"/><line x1="55" y1="57" x2="47" y2="68" className="ill-body"/><line x1="55" y1="57" x2="65" y2="68" className="ill-body"/><line x1="48" y1="50" x2="46" y2="34" className="ill-body"/><line x1="66" y1="50" x2="68" y2="34" className="ill-body"/><line x1="40" y1="32" x2="52" y2="32" className="ill-bar"/><line x1="62" y1="32" x2="74" y2="32" className="ill-bar"/><line x1="18" y1="61" x2="78" y2="61" className="ill-bench"/></Frame>
      <Frame x={180}>{person(36,38)}<line x1="41" y1="43" x2="57" y2="57" className="ill-body"/><line x1="55" y1="57" x2="47" y2="68" className="ill-body"/><line x1="55" y1="57" x2="65" y2="68" className="ill-body"/><line x1="48" y1="50" x2="30" y2="40" className="ill-body"/><line x1="66" y1="50" x2="84" y2="40" className="ill-body"/><line x1="25" y1="38" x2="34" y2="43" className="ill-bar"/><line x1="80" y1="43" x2="89" y2="38" className="ill-bar"/><line x1="18" y1="61" x2="78" y2="61" className="ill-bench"/></Frame>
    </>}
   </svg>
 </div>
}
function WorkoutPage({data,workout,updateData}){
 const library=data.exerciseLibrary||defaultExercises;
 const [finished,setFinished]=useState(Boolean(data.finishedWorkouts?.[todayKey()]));
const[muscle,setMuscle]=useState("Chest"),[selected,setSelected]=useState(library.Chest?.[0]||"Bench Press"),[sets,setSets]=useState(workout[library.Chest?.[0]]||[{kg:10,reps:8,done:false},{kg:10,reps:8,done:false},{kg:10,reps:8,done:false}]),[manage,setManage]=useState(false),[newExercise,setNewExercise]=useState("");const selectExercise=name=>{setSelected(name);setSets(workout[name]||[{kg:10,reps:8,done:false},{kg:10,reps:8,done:false},{kg:10,reps:8,done:false}])};const saveSets=next=>{setSets(next);updateData({workoutsByDay:{...data.workoutsByDay,[todayKey()]:{...workout,[selected]:next}}})};const addSet=()=>saveSets([...sets,{kg:sets.at(-1)?.kg||10,reps:sets.at(-1)?.reps||8,done:false}]);const addExercise=()=>{const n=newExercise.trim();if(!n)return;const next={...library,[muscle]:[...(library[muscle]||[]),n]};updateData({exerciseLibrary:next});setNewExercise("");setSelected(n);setSets([{kg:10,reps:8,done:false},{kg:10,reps:8,done:false},{kg:10,reps:8,done:false}])};const rename=name=>{const n=prompt("New exercise name",name)?.trim();if(!n||n===name)return;const next={...library,[muscle]:(library[muscle]||[]).map(x=>x===name?n:x)};const wd=data.workoutsByDay[todayKey()]||{};if(wd[name]){wd[n]=wd[name];delete wd[name]}updateData({exerciseLibrary:next,workoutsByDay:{...data.workoutsByDay,[todayKey()]:wd}});setSelected(n)};const del=name=>{if((library[muscle]||[]).length<=1)return;if(!confirm(`Delete ${name} from ${muscle}?`))return;const next={...library,[muscle]:(library[muscle]||[]).filter(x=>x!==name)};updateData({exerciseLibrary:next});if(selected===name)selectExercise(next[muscle][0])};const finish=()=>{
 const currentWorkout={...workout,[selected]:sets};
 const doneExercises=Object.entries(currentWorkout).filter(([,v])=>Array.isArray(v)&&v.some(s=>s.done)).length;
 updateData({
   workoutsByDay:{...data.workoutsByDay,[todayKey()]:currentWorkout},
   finishedWorkouts:{...(data.finishedWorkouts||{}),[todayKey()]:{
     time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),
     exercises:doneExercises,
     totalSets:Object.values(currentWorkout).reduce((a,v)=>a+(Array.isArray(v)?v.filter(s=>s.done).length:0),0)
   }}
 });
 setFinished(true);
};return <section className="page"><div className="pageTitle"><div><span className="label">EXERCISE LIBRARY</span><h2>Train</h2></div><button className={manage?"round manageOn":"round"} onClick={()=>setManage(!manage)}><Settings size={18}/></button></div>{manage&&<div className="card manager"><b>Manage {muscle} exercises</b><div className="addExerciseRow"><input value={newExercise} onChange={e=>setNewExercise(e.target.value)} placeholder={`New ${muscle} exercise`}/><button onClick={addExercise}><Plus size={17}/></button></div><p>Add, rename or delete exercises in the selected body-part library.</p></div>}{finished&&<div className="finishBanner"><Check size={18}/><div><b>Workout saved ✓</b><span>Today's workout has been recorded.</span></div><button onClick={()=>setFinished(false)}><X size={15}/></button></div>}<div className="muscleTabs">{Object.keys(library).map(m=><button className={muscle===m?"sel":""} onClick={()=>{setMuscle(m);selectExercise(library[m][0])}} key={m}>{m}</button>)}</div><div className="exercisePicker">{(library[muscle]||[]).map(e=><div className="exerciseChip" key={e}><button className={selected===e?"selected":""} onClick={()=>selectExercise(e)}>{e}</button>{manage&&<div className="chipTools"><button onClick={()=>rename(e)}><Pencil size={12}/></button><button onClick={()=>del(e)}><Trash2 size={12}/></button></div>}</div>)}</div><div className="card exercise"><div className="exerciseHeadWithVisual"><div className="exerciseHead"><div><span className="label">{muscle.toUpperCase()}</span><h3>{selected}</h3><span>Log your weight and reps for every set.</span></div><Dumbbell/></div><ExerciseIllustration name={selected}/></div><div className="setHead"><span>SET</span><span>WEIGHT</span><span>REPS</span><span>DONE</span></div>{sets.map((s,i)=><div className="setRow" key={i}><span>{i+1}</span><select value={s.kg} onChange={e=>saveSets(sets.map((x,j)=>j===i?{...x,kg:Number(e.target.value)}:x))}>{weightOptions.map(w=><option key={w}>{w}</option>)}</select><select value={s.reps} onChange={e=>saveSets(sets.map((x,j)=>j===i?{...x,reps:Number(e.target.value)}:x))}>{repOptions.map(r=><option key={r}>{r}</option>)}</select><button className={s.done?"done":""} onClick={()=>saveSets(sets.map((x,j)=>j===i?{...x,done:!x.done}:x))}>✓</button></div>)}<button className="addSet" onClick={addSet}>+ ADD SET</button></div><button className="widePrimary" onClick={finish}><Check size={17}/> FINISH WORKOUT</button></section>}
function ProgressPage({data,addWeight}){const[w,setW]=useState(data.weight),h=data.weightHistory||[],min=Math.min(...h.map(x=>x.weight),data.weight)-.5,max=Math.max(...h.map(x=>x.weight),data.weight)+.5;return <section className="page"><div className="pageTitle"><div><span className="label">PROGRESS</span><h2>Your journey</h2></div></div><div className="statGrid"><div className="stat"><span>CURRENT</span><b>{Number(data.weight).toFixed(1)} kg</b></div><div className="stat"><span>GOAL</span><b>{data.goalWeight} kg</b></div><div className="stat"><span>TO GO</span><b>{Math.max(0,data.goalWeight-data.weight).toFixed(1)} kg</b></div></div><div className="card chart"><div className="cardHead"><div><span className="label">BODY WEIGHT</span><h3>Saved entries</h3></div><TrendingUp/></div><div className="spark">{h.slice(-14).map((v,i,a)=><div className="point" key={i} style={{left:`${a.length===1?50:i/(a.length-1)*90+5}%`,bottom:`${(v.weight-min)/(max-min)*75+10}%`}}><b>{v.weight}</b></div>)}</div></div><div className="card inputCard"><label>LOG TODAY'S WEIGHT</label><div className="weightInput"><input inputMode="decimal" value={w} onChange={e=>setW(e.target.value)}/><span>kg</span><button onClick={()=>addWeight(Number(w))}>SAVE</button></div></div></section>}
function SettingsPage({data,update}){return <section className="page"><div className="pageTitle"><div><span className="label">N-FIT</span><h2>Settings</h2></div></div><div className="card settings"><h3>Your targets</h3><label>Daily calories</label><input type="number" value={data.calGoal} onChange={e=>update({calGoal:Number(e.target.value)})}/><label>Daily protein (g)</label><input type="number" value={data.proteinGoal} onChange={e=>update({proteinGoal:Number(e.target.value)})}/><label>Goal weight (kg)</label><input type="number" step="0.1" value={data.goalWeight} onChange={e=>update({goalWeight:Number(e.target.value)})}/><label>Water goal (L)</label><input type="number" step="0.1" value={data.waterGoal} onChange={e=>update({waterGoal:Number(e.target.value)})}/><div className="settingLine"><span>Storage</span><b>Saved on this device</b></div><div className="settingLine"><span>App version</span><b>V4.0</b></div></div></section>}
createRoot(document.getElementById("root")).render(<App/>);
